# Daniel Lara <danniel@fedoraproject.org>, 2016. #zanata
# Marco Aurélio Krause <ouesten@me.com>, 2016. #zanata
# Filipe Rosset <rosset.filipe@gmail.com>, 2017. #zanata
# Luiz Fernando Pereira <luizfernandopereira@outlook.com.br>, 2018. #zanata
# Cássio Rodrigo Honorato Rodrigues <cassiorhr@outlook.com>, 2019. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-11-17 09:18-0500\n"
"PO-Revision-Date: 2019-08-03 08:01+0000\n"
"Last-Translator: Cássio Rodrigo Honorato Rodrigues <cassiorhr@outlook.com>\n"
"Language-Team: Portuguese (Brazil)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 4.6.2\n"

#: plugins/kickstart.py:57
msgid "Install packages defined in a kickstart file on your system"
msgstr ""
"Instalar em seu sistema os pacotes definidos em um arquivo do kickstart"

#: plugins/kickstart.py:62
msgid "kickstart file"
msgstr "arquivo kickstart"

#: plugins/kickstart.py:80
#, python-format
msgid "file cannot be parsed: %s"
msgstr "arquivo não pode ser analisado: %s"

#: plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Adicionando '{}' para a lista de pacotes de manipulação para o rpmconf"

#: plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "O plugin rpmconf não será executado em modo não interativo"

#: plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "ignorando sys.exit de rpmconf devido a falta da variável MERGE"

#: plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "ignorando sys.exit de rpmconf devido a falta de arquivo"

#: plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr "mostrar todas variáveis dnf ativa"

#: plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "conexão com o snapperd falhou: %s"

#: plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr "criando pre_snapshot"

#: plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr "pre_snapshot %d criado"

#: plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr "criando pre_snapshot falhou: %s"

#: plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr "pulando post_snapshot porque a criação de pre_snapshot falhou"

#: plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr "criando post_snapshot"

#: plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr "post_snapshot %d criado"

#: plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr "criando post_snapshot falhou: %s"

#. Translators: This string is only used in unit tests.
#: plugins/system_upgrade.py:46
msgid "the color of the sky"
msgstr "a cor do céu"

#: plugins/system_upgrade.py:60
msgid "Need a --releasever greater than the current system version."
msgstr "Necessita de um --releasever maior que o da versão do sistema atual."

#. Translators: do not change "reboot" here
#: plugins/system_upgrade.py:62
#, python-brace-format
msgid ""
"Download complete! Use 'dnf {command} reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf {command} clean'"
msgstr ""

#: plugins/system_upgrade.py:65
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""
"Desculpe, você precisa utilizar 'download --releasever' ao invés de '--"
"network'"

#: plugins/system_upgrade.py:74
msgid "Reboot turned off, not rebooting."
msgstr ""

#: plugins/system_upgrade.py:123
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr ""

#: plugins/system_upgrade.py:143
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr ""

#: plugins/system_upgrade.py:289
msgid "The following boots appear to contain upgrade logs:"
msgstr "As seguintes inicializações parecem conter registros de atualizações:"

#: plugins/system_upgrade.py:299
msgid "-- no logs were found --"
msgstr "-- nenhum registro encontrado --"

#: plugins/system_upgrade.py:314
msgid "Cannot find logs with this index."
msgstr "Não foi possível encontrar registros com este índice."

#: plugins/system_upgrade.py:323
msgid "Unable to match systemd journal entry"
msgstr "Não é possível corresponder à entrada no diário do systemd"

#: plugins/system_upgrade.py:344
msgid "Prepare system for upgrade to a new release"
msgstr "Preparar o sistema para atualizar para uma nova versão"

#: plugins/system_upgrade.py:358
msgid "keep installed packages if the new release's version is older"
msgstr "manter os pacotes instalados se os da nova versão forem mais antigos"

#: plugins/system_upgrade.py:362
msgid "which logs to show"
msgstr "quais logs exibir"

#: plugins/system_upgrade.py:396
#, python-brace-format
msgid "Incompatible version of data. Rerun 'dnf {command} download [OPTIONS]'"
msgstr ""

#: plugins/system_upgrade.py:433
msgid "Command 'offline-distrosync' cannot be used with --no-downgrade option"
msgstr ""

#: plugins/system_upgrade.py:455
msgid "Additional information for System Upgrade: {}"
msgstr ""

#: plugins/system_upgrade.py:458
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"Antes de continuar certifique-se que o seu sistema está totalmente "
"atualizado rodando \"dnf --refresh upgrade\". Você quer continuar"

#: plugins/system_upgrade.py:462
msgid "Operation aborted."
msgstr "Operação abortada."

#: plugins/system_upgrade.py:520
msgid "system is not ready for upgrade"
msgstr "o sistema não está pronto para uma atualização"

#: plugins/system_upgrade.py:523
#, python-brace-format
msgid ""
"the transaction was not prepared for '{command}'. Rerun 'dnf {command} "
"download [OPTIONS]'"
msgstr ""

#: plugins/system_upgrade.py:527
msgid "upgrade is already scheduled"
msgstr "a atualização já está agendada"

#: plugins/system_upgrade.py:533
msgid "trigger file does not exist. exiting quietly."
msgstr "O arquivo de gatilho não existe. Saindo silenciosamente."

#: plugins/system_upgrade.py:536
msgid "another upgrade tool is running. exiting quietly."
msgstr "outra ferramenta de atualização em execução. saindo silenciosamente."

#: plugins/system_upgrade.py:545
#, python-brace-format
msgid "use 'dnf {command} reboot' to begin the upgrade"
msgstr ""

#: plugins/system_upgrade.py:563
msgid "Rebooting to perform upgrade."
msgstr "Reiniciando para realizar a atualização."

#: plugins/system_upgrade.py:596
msgid "Starting offline upgrade. This will take a while."
msgstr ""

#: plugins/system_upgrade.py:598
msgid "Starting offline distrosync. This will take a while."
msgstr ""

#: plugins/system_upgrade.py:600
msgid "Starting system upgrade. This will take a while."
msgstr "Iniciando a atualização do sistema. Isso vai levar algum tempo."

#: plugins/system_upgrade.py:616
msgid "Cleaning up downloaded data..."
msgstr "Limpando os dados descarregados..."

#: plugins/system_upgrade.py:648
msgid "Transaction saved to {}."
msgstr ""

#: plugins/system_upgrade.py:651
msgid "Error storing transaction: {}"
msgstr ""

#: plugins/system_upgrade.py:673
msgid "Download finished."
msgstr "Download concluído."

#: plugins/system_upgrade.py:676 plugins/system_upgrade.py:677
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Atualização completa! Limpando e reiniciando..."

#: plugins/system_upgrade.py:686
msgid "Prepare offline upgrade of the system"
msgstr ""

#: plugins/system_upgrade.py:691
msgid "Prepare offline distrosync of the system"
msgstr ""

#: plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "Desativando o plugin torproxy: não poderá se conectar à rede Tor"

#: plugins/tracer.py:69
msgid "For more information run:"
msgstr "Para mais informações execute:"

#: plugins/tracer.py:96
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Chamada para Tracer API terminou inesperadamente:"

#: plugins/tracer.py:98
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Visite https://github.com/FrostyX/tracer/issues e envie o problema. Obrigado"

#: plugins/tracer.py:100
msgid "We apologize for any inconvenience"
msgstr "Nos desculpamos por qualquer inconveniência"

#~ msgid "Unable to match package: %s"
#~ msgstr "Não foi possível corresponder o pacote: %s"

#~ msgid "Unable to match some of packages"
#~ msgstr "Não foi possível corresponder algum dos pacotes"
